Adding credits to front end
YACS-RCOS/yacs.n pull request #327
Opened 2020-11-15 01:44 UTC by gizzon

**Issue**

This PR doesn't close an issue per se, but rather builds upon a recent PR that added credits to the database. This PR utilizes those entries and displays them on the website. These changes can be seen:

1) As a credit counter under the CRNs list
2) On the course info popup while on schedule
3) On the course page

**Database Changes/Migrations**

No database changes

**Photos**
<img width="546" alt="Messages Image(1113238466)" src="https://user-images.githubusercontent.com/35758479/99160888-3b900980-26ba-11eb-8621-d3a2a5c36d22.png">
<img width="779" alt="Messages Image(1552780918)" src="https://user-images.githubusercontent.com/35758479/99160890-3b900980-26ba-11eb-8f49-5bcef6a12f21.png">
<img width="683" alt="Messages Image(2021742158)" src="https://user-images.githubusercontent.com/35758479/99160891-3b900980-26ba-11eb-8c16-80324e7def90.png">
<img width="511" alt="Messages Image(3966734186)" src="https://user-images.githubusercontent.com/35758479/99160893-3c28a000-26ba-11eb-9536-57cd16f93d00.png">

2020-11-18 02:20 UTC, marchdan commented
@jshom Do you know why there is no temp deploy on here?

2020-11-18 04:57 UTC, jshom commented
@marchdan not sure, maybe we need a merge/rebase from master

2020-11-18 17:20 UTC, IkeLyons requested changes
Looks good! just a couple small changes

2020-11-18 17:20 UTC, IkeLyons commented on src/web/src/pages/CourseScheduler.vue
> +      <span v-if= "courseInfoModalCourse.min_credits != courseInfoModalCourse.max_credits">
Think this could just be a v-else

2020-11-18 17:20 UTC, IkeLyons commented on src/web/src/pages/CoursePage.vue
> +      if (this.courseObj.min_credits != this.courseObj.min_credits){
I think this is a typo, left hand side should probably be `this.courseObj.max_credits`?

2020-11-21 23:42 UTC, RichtXO commented
With all the issues away, this looks nice! Let's try to get the credits displayed while the user is exploring the courses in the explore tab.

2020-11-22 18:51 UTC, IkeLyons approved these changes

2020-11-22 18:56 UTC, marchdan commented
> With all the issues away, this looks nice! Let's try to get the credits displayed while the user is exploring the courses in the explore tab.

@RichtXO Is this something that still needs to be added to this PR?

2020-11-22 19:02 UTC, RichtXO commented
> > With all the issues away, this looks nice! Let's try to get the credits displayed while the user is exploring the courses in the explore tab.
> 
> @RichtXO Is this something that still needs to be added to this PR?

I guess we can make another issue for it, but I think it's best to add them in at the same time.

2020-11-22 20:06 UTC, RichtXO commented
Going more in details, I see that there's a screenshot having the credits in the explore page, but for some reason, I don't see it on my end.

2020-11-22 23:29 UTC, gizzon commented
> Going more in details, I see that there's a screenshot having the credits in the explore page, but for some reason, I don't see it on my end.

Thanks for making those changes Rich. I was having trouble pushing my changes. I'm not sure why you're having that issue. I'll check it out now.

2020-11-23 00:02 UTC, jshom commented on src/web/src/pages/CoursePage.vue
> +      breadcrumbNav: [
Please remove spare space at the end of the line

2020-11-23 00:45 UTC, jshom commented on src/web/src/pages/CourseScheduler.vue
> +    },
hi proglang

2020-11-23 00:46 UTC, jshom approved these changes

2020-11-23 00:46 UTC, merged