294 - breadcrumb nav on explore pages
YACS-RCOS/yacs.n pull request #328
Opened 2020-11-16 02:03 UTC by nick-lennox

**Issue**

issue #294 
"When I am on a course page or subject page I want to know relatively where I am on the YACS page."

*Example:*
Added breadcrumb navigation on all subpages of /explore

**Test Procedure**

Go to YACS home -> explore, notice the row below the header that tells you where you are relative to the rest of the YACS pages

**Photos**

![Screen Shot 2020-11-15 at 9 02 01 PM](https://user-images.githubusercontent.com/44211696/99205233-e9b4b580-2785-11eb-965f-138295bc35d1.png)

2020-11-16 04:22 UTC, 123joshuawu requested changes
Sweet, looks really nice.

Just two things:
1) I think we don't need `Home` in the breadcrumb because `Explore` is the root page for all the explore pages
2) Can we use `to` instead of `href` for the links? This will avoid reloading the page when using the breadcrumbs

2020-11-17 01:42 UTC, nick-lennox commented
> 1. I think we don't need `Home` in the breadcrumb because `Explore` is the root page for all the explore pages

I feel like it may not be a bad idea to leave it in to make the navigation back to the main page a bit easier (we also don't necessarily need to call it 'Home'), but if you feel strongly about it I can definitely change it. For sure I'll change the hrefs though.

Thanks for the feedback!

2020-11-17 03:58 UTC, 123joshuawu approved these changes
Sounds good to me

2020-11-17 16:15 UTC, marchdan commented
@nick-lennox @123joshuawu What about if we used "YACS" instead of "Home"? I do agree that Explore is kinda a root page, but explore is still a branch off of the root homepage. this is just a thought, I think either way works fine

2020-11-17 17:40 UTC, nick-lennox commented
> @nick-lennox @123joshuawu What about if we used "YACS" instead of "Home"? I do agree that Explore is kinda a root page, but explore is still a branch off of the root homepage. this is just a thought, I think either way works fine

I was thinking this would be a good solution too.

2020-11-17 21:59 UTC, marchdan commented
@nick-lennox Please resolve merge conflicts so this can be reviewed

2020-11-18 02:14 UTC, marchdan commented on src/web/src/pages/SubjectExplorer.vue
> +      <!-- left column of courses -->
Is there a specific reason for the extra spacing here?

2020-11-18 02:15 UTC, marchdan commented
Is there a specific reason for the extra spacing change in this file?

https://github.com/YACS-RCOS/yacs.n/pull/328/files#diff-a09f667c120da1ee7f101c7058309ff0ed6bbfd9432a1077ad7c0cd480d00257

2020-11-19 00:37 UTC, marchdan approved these changes
Looks good. Course explorer seems to have some weird loading issues, but I think there is a separate PR to fix that

2020-11-19 00:40 UTC, marchdan commented
@123joshuawu Could you double-check this? Looks good to me, but there have been changes since you approved

2020-11-19 00:57 UTC, 123joshuawu approved these changes

2020-11-19 01:01 UTC, merged