Mobile UI fixes
YACS-RCOS/yacs.n pull request #366
Opened 2020-12-03 01:02 UTC by nick-lennox

**Issue**

closes #338 

**Test Procedure**

Navigate to Explore -> {dept} on mobile/reduced-size window. Displays two columns with each course in the department. Previously the user wouldn't be able to scroll left on this page and not all classes would be visible. 

**Photos**
Before: 
<img src="https://user-images.githubusercontent.com/44211696/100949438-4929f980-34d8-11eb-9931-0f6f02b989b5.png" width="50%" height="50%">

After:
<img src="https://user-images.githubusercontent.com/44211696/100949168-a07b9a00-34d7-11eb-936f-23888ecc1d7b.png" width="50%" height="50%">
<img src="https://user-images.githubusercontent.com/44211696/100949169-a07b9a00-34d7-11eb-89ed-89c2c88e2936.png" width="100%" height="100%">

**Additional Info**

I justified the department name centrally, not sure if this was ignored for any particular reason but it seemed to make the UI a bit better in my opinion, but I can change it if need be. For overflow in each courseBox I made it scrollable within that box, but again if we want to change that to something else we definitely can.

2020-12-03 01:29 UTC, jshom commented
@nick-lennox can you resolve merge conflicts, blocking temp deploy. thx!

2020-12-03 02:14 UTC, 123joshuawu commented
maybe on mobile the courses should be listed in a single column? The title's seem a little cluttered to me

2020-12-03 21:31 UTC, nick-lennox commented
> maybe on mobile the courses should be listed in a single column? The titles' seem a little cluttered to me

While I think that'd be fine for most majors, for certain majors that have a ton of courses (CSCI for example) it's a lot of scrolling. I originally implemented it as one column and after talking with @jshom I changed it to two. I still do agree though that the titles are a bit clustered.

2020-12-06 19:38 UTC, 123joshuawu requested changes

2020-12-06 19:38 UTC, 123joshuawu commented on src/web/src/pages/SubjectExplorer.vue
> +
We probably don't want to change this. These changes were made part of #337. It would probably be best to leave it as is as much as possible

2020-12-08 23:40 UTC, marchdan commented
@nick-lennox What is the current status of this?

2020-12-14 00:48 UTC, 123joshuawu approved these changes

2020-12-27 00:44 UTC, merged