Darker Dark Mode
YACS-RCOS/yacs.n pull request #464
Opened 2021-07-19 02:20 UTC by NickKing24

Was working on a different issue, but decided to quickly implement a dark mode color scheme for the course schedule.

**Photos**

Before:
![image](https://user-images.githubusercontent.com/78986301/126093436-2354099a-ab16-4cdb-add2-4fff35e43312.png)

After:
![image](https://user-images.githubusercontent.com/78986301/126093491-b22f7508-7b57-4415-99a7-1cc92bc4c3f5.png)

2021-07-19 02:22 UTC, marchdan commented
@NickKing24 Did you make a linked issue for this?

2021-07-19 02:34 UTC, NickKing24 commented
Oh, oops no. I'll do that right now.

2021-07-21 01:10 UTC, antmcgrann approved these changes
Looks good an runs properly.

2021-07-21 01:13 UTC, marchdan commented
Do these changes work correctly in color-blind mode?

2021-07-21 02:39 UTC, marchdan requested changes
The changes made do not account directly for color-blind mode. If the purpose is to adapt the colors to better fit dark mode, see if you can accommodate color-blind dark mode.

2021-07-23 18:15 UTC, NickKing24 commented
As of now, the color blind mode takes precedence over dark mode. I could implement a color blind dark mode, but it would be a delicate procedure to adjust the colors and make them darker while keeping them color blind friendly, so it might take a while.

2021-07-23 18:54 UTC, marchdan commented
> As of now, the color blind mode takes precedence over dark mode. I could implement a color blind dark mode, but it would be a delicate procedure to adjust the colors and make them darker while keeping them color blind friendly, so it might take a while.

I have no issue with keeping the color-blind mode the same, I just wanted to make you aware of it in case it was something you intended to implement.

2021-08-10 01:16 UTC, NickKing24 commented
Sorry for the late response, I've been really busy lately. I think I want to leave it like this for now and maybe implement a color blind dark mode in the future.

2021-08-10 14:19 UTC, marchdan commented
> Sorry for the late response, I've been really busy lately. I think I want to leave it like this for now and maybe implement a color blind dark mode in the future.

I'll re-review as is then and make sure the rest looks good

2021-09-29 03:31 UTC, RichtXO approved these changes
LGTM! :+1:

2021-09-29 03:53 UTC, Viyerelu23333 approved these changes
Looks good to me.

`hsla()` or `rgba()` could better preserve the colors (minimize the diffs with light modes).  But not for this PR I guess...

2021-10-01 20:53 UTC, merged