Fixed scrollbar darkmode
YACS-RCOS/yacs.n pull request #471
Opened 2021-07-23 18:09 UTC by antmcgrann

closes #465 

Fixes issue of scrollbar not changing colors after you switch to/from dark mode

2021-07-23 18:48 UTC, marchdan commented on rpi_data/modules/fetch_catalog_course_info.py
> +    print(acalog_api_key)
Was this print left in on purpose?

2021-07-23 18:51 UTC, marchdan requested changes
Using page reloads to fix this issue is bulky and does not present well on the temp deploy. You might look at how other sections of the site handle the dark mode toggle for everything without having to do a page reload.

2021-07-23 18:52 UTC, Viyerelu23333 commented
Not sure if refreshing on color change is the best way to solve it...  
And your refresh did not catch the media queries changes.

Firefox does provide a good solution to this by detecting the background of the box automatically.  Safari overwrites the UA styles, so the scrollbar is transparent and color-aware.  However, Chrome will only detect the `color-scheme` meta tag.  

Admittedly, the `color-scheme` can be `light dark` to specify both modes.  But in stylesheet, we are not using media queries to detect the dark mode, so Chrome cannot detect what mode is it currently and fallbacks to `light`.  Then the scrollbars are in light.

A possible fix to this bug is to make the `color-scheme` dynamically or change the stylesheets...

2021-07-23 18:57 UTC, marchdan commented
@Viyerelu23333 The scroll bar wouldn't have a `fill= "currentcolor"' property, would it?

2021-07-23 19:05 UTC, Viyerelu23333 commented
> @Viyerelu23333 The scroll bar wouldn't have a `fill= "currentcolor"` property, would it?

There are CSS selectors for that.  In WebKit, use `::-webkit-scrollbar-thumb { background-color }` and `::-webkit-scrollbar-track { background-color }`.  But this breaks the UA styles.

2021-10-01 20:35 UTC, closed without merging

2021-10-01 20:36 UTC, EthanTuttle commented
Developer's fix wasn't accepted and is no longer active, closing this branch and pull request. Someone else please take over the issue (maybe @SamooMei, he's pretty good at this stuff)