Color Mode Button/Notification UI Changed
YACS-RCOS/yacs.n pull request #662
Opened 2023-02-24 04:00 UTC by mlammon11

- Changed the notification button to a switch to be more intuitive to the user
- Added brief text in front so the user instantly knows the function of the switch
- Moved toast notification to the top-center of the screen so that it doesn't interfere with clicking the switch/moon

**Issue**
> closes #651

**Database Changes/Migrations**

Nothing changed here 

**Test Modifications**

Nothing changed here 

**Test Procedure**
- Use the new switch to change from light/dark mode
- Double click moon to see the notification moved to the top-middle of the screen, allowing you to adjust your settings without notification in your way

**Photos**
Old
![image](https://user-images.githubusercontent.com/91478985/221088098-2e42659a-842c-47a7-9a19-10f7f619f955.png)

New
![image](https://user-images.githubusercontent.com/91478985/221088026-60456255-4581-4432-8960-f9ca7d64c3a7.png)

Old
![image](https://user-images.githubusercontent.com/91478985/221088161-add57c40-3ed2-4140-a4eb-80574734da56.png)

New 
![image](https://user-images.githubusercontent.com/91478985/221088288-7080d424-69db-4059-8022-2a4f41deab9f.png)

**Additional Info**

2023-02-24 22:36 UTC, dorian451 requested changes
looks good so far,
can you make the moon more obviously clickable

2023-03-15 22:26 UTC, jonha1 approved these changes
looks awesome, improved user experience

2023-03-17 20:22 UTC, dorian451 requested changes

2023-03-17 20:22 UTC, dorian451 commented on src/web/src/components/Header.vue
> +        <b-nav-dropdown text="Color Mode" style="padding-right: 5px">
can you make it so that the currently selected mode is highlighted or something

2023-03-24 21:23 UTC, zhengw5 approved these changes
Function works just as the coder says. I am not entirely sure if I like the feature better but it is more intuitive.

2023-03-31 20:45 UTC, dorian451 requested changes
it doesn't follow device theme after the initial load, and doesn't allow user to change theme until after they select "follow device theme"

2023-04-04 21:22 UTC, dorian451 approved these changes
finally works, yay!

2023-04-05 20:24 UTC, jonha1 approved these changes
looks great

2023-04-07 00:55 UTC, merged