Front end integration
YACS-RCOS/yacs.n pull request #752
Opened 2023-07-14 18:25 UTC by jonha1

Issue #703 

**Database Changes/Migrations**

Created professors tables to allow professors to be stored in the backend

**Test Procedure**

Try importing the Professors.JSON file

*Example:*
> 1. go to losthost admin
> 2. go to import professors VIA JSON
> 3. Select Professors.JSON file.
> 4. Upload the file.
> 5. You shouldreceive a message saying JSON imported succesfully

2023-07-21 17:59 UTC, mlammon11 approved these changes
Importing professors json file works as intended. just add to pull request description where to find professor.json file in yacs folder.

2023-08-08 18:19 UTC, Acewvrs approved these changes

2023-08-08 18:21 UTC, doinglin approved these changes

2023-09-22 04:50 UTC, dorian451 requested changes
Looks good, but I can't see the professor page anywhere :(

2023-10-13 20:40 UTC, dorian451 approved these changes
gonna trust you on this one

2023-10-13 20:42 UTC, merged